### ISSUE TITLE
`sweep` function DimensionMismatch

### ISSUE THREAD

**Issue by mingsnu** [panlanfeng/RFlavor.jl#6]
```
x = hcat(ones(10), rand(10))
sweep(x, 2, mean(x,1))
```

The above code returns a **DimensionMismatch** error because `mean(x, 1)` returns a 1x2 array.

**Comment by mingsnu** [comment]
Also need `sweep(Array, Int, Real)` method

```
sweep(x, 1, 1.0) 
```

**Comment by panlanfeng** [comment]
I see. We need a function `array` similar to `matrix` to fix this.

**Comment by panlanfeng** [comment]
This should be fixed by [this commit](https://github.com/panlanfeng/RFlavor.jl/commit/dd9efb80a57f241ddb81316a4199321b4090bb27)
